name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Build HTML
      run: |
        sudo apt-get install libopenblas-base
        python -m pip install --user sphinx==5.0.2 sphinx-rtd-theme sphinxcontrib-apidoc
        python -m pip install -r docs/adcc_requirements.txt -v
        python -m pip install --user adcc
        python setup.py build_sphinx
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: build/sphinx/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/sphinx/html

